# Generated by Django 4.0.3 on 2022-04-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_canvasdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasdata',
            name='data',
            field=models.TextField(unique=True),
        ),
    ]
