# Generated by Django 4.0.3 on 2022-04-13 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 13, 19, 37, 13, 341769, tzinfo=utc)),
        ),
    ]
