# Generated by Django 4.0.3 on 2022-04-16 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0005_alter_check_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 15, 24, 2, 705506, tzinfo=utc)),
        ),
    ]
